import pg from "pg";
import { afterAll,beforeEach,describe,expect,it } from "vitest";
import { AgentRepository,RunRepository } from "../../src/db/repositories.js";
import type { Principal } from "../../src/db/types.js";
import { ProviderRegistry } from "../../src/models/provider-registry.js";
import { ExecutionEngineRegistry } from "../../src/execution/execution-engine-registry.js";
import { NativeExecutionEngine } from "../../src/execution/native-engine.js";
import { createToolRegistry } from "../../src/tools/registry.js";
import { AgentLoop } from "../../src/execution/agent-loop.js";
import { LifecycleWorker } from "../../src/worker/worker.js";
import { DeterministicTestProvider,type DeterministicReply } from "../support/deterministic-provider.js";
import { ModelProviderError } from "../../src/models/model-errors.js";

const { Pool }=pg;const pool=new Pool({connectionString:process.env.DATABASE_URL??"postgres://agent:agent@localhost:5432/agent_platform"});
const principal:Principal={tenantId:"77777777-7777-4777-8777-777777777777",userId:"88888888-8888-4888-8888-888888888888",roles:[]};
beforeEach(async()=>pool.query("TRUNCATE structured_notes,audit_events,usage_records,approvals,model_attempts,tool_executions,worker_leases,checkpoints,steps,runs,agents CASCADE"));afterAll(async()=>pool.end());

async function setup(replies:DeterministicReply[],options:{tools?:string[];maxSteps?:number;tokenBudget?:number;costBudget?:number;inputRate?:number;outputRate?:number}={}){const provider=new DeterministicTestProvider(replies);const providers=new ProviderRegistry();providers.register(provider);const engines=new ExecutionEngineRegistry();engines.register(new NativeExecutionEngine());const registry=createToolRegistry(pool);const loop=new AgentLoop(pool,providers,engines,registry);const agent=await new AgentRepository(pool).create(principal,{name:`model-${crypto.randomUUID()}`,systemInstructions:"Return a canonical action.",model:{provider:provider.id,model:"deterministic",maxOutputTokens:100,timeoutMs:1000,inputCostMicrousdPerMillion:options.inputRate??0,outputCostMicrousdPerMillion:options.outputRate??0,cachedCostMicrousdPerMillion:0},allowedTools:options.tools??[],maximumSteps:options.maxSteps??10,tokenBudget:options.tokenBudget??1000,costBudgetMicrousd:options.costBudget??1000,approvalPolicy:{},outputSchema:null});const run=await new RunRepository(pool).create(principal,agent.id,"complete the test goal");const worker=new LifecycleWorker(pool,{workerId:"model-worker",leaseSeconds:30},{execute:(id,workerId)=>loop.execute(id,workerId,principal.roles)});return{provider,run,worker};}

describe("canonical Stage 3 loop",()=>{
  it("persists model attempts, routes a tool through the canonical executor, and completes",async()=>{const {run,worker}=await setup([{toolCalls:[{id:"calc-call",name:"calculator",arguments:{expression:"2+3*4"}}]},{body:{type:"final_answer",output:{answer:14}}}],{tools:["calculator"]});expect(await worker.tick()).toBe(true);const stored=await new RunRepository(pool).get(principal.tenantId,run.id);expect(stored.status).toBe("completed");expect(stored.finalOutput).toEqual({answer:14});expect(Number((await pool.query("SELECT count(*) AS count FROM model_attempts WHERE run_id=$1 AND status='succeeded'",[run.id])).rows[0].count)).toBe(2);expect(Number((await pool.query("SELECT count(*) AS count FROM tool_executions WHERE run_id=$1 AND status='succeeded'",[run.id])).rows[0].count)).toBe(1);expect(Number((await pool.query("SELECT count(*) AS count FROM steps WHERE run_id=$1 AND kind='model'",[run.id])).rows[0].count)).toBe(2);});
  it("rejects an unauthorized tool proposal",async()=>{const {run,worker}=await setup([{body:{type:"call_tool",toolName:"structured_note_storage",arguments:{title:"x",body:"y",tags:[]}}}],{tools:["calculator"]});await expect(worker.tick()).rejects.toThrow(/not allowed/);expect((await new RunRepository(pool).get(principal.tenantId,run.id)).status).toBe("failed");expect(Number((await pool.query("SELECT count(*) AS count FROM structured_notes")).rows[0].count)).toBe(0);});
  it("fails malformed actions safely",async()=>{const {run,worker}=await setup([{body:{unexpected:true}}]);await expect(worker.tick()).rejects.toThrow(/canonical agent action/);expect((await new RunRepository(pool).get(principal.tenantId,run.id)).status).toBe("failed");expect((await pool.query("SELECT status,normalized_error_code FROM model_attempts WHERE run_id=$1",[run.id])).rows[0]).toEqual(expect.objectContaining({status:"failed",normalized_error_code:"malformed_response"}));});
  it("persists provider failure without corrupting lifecycle state",async()=>{const {run,worker}=await setup([{error:new ModelProviderError("unavailable","offline",true)}]);await expect(worker.tick()).rejects.toThrow("offline");expect((await new RunRepository(pool).get(principal.tenantId,run.id)).status).toBe("failed");expect((await pool.query("SELECT status,normalized_error_code FROM model_attempts WHERE run_id=$1",[run.id])).rows[0]).toEqual(expect.objectContaining({status:"failed",normalized_error_code:"unavailable"}));});
  it("honors cancellation before provider invocation",async()=>{const setupResult=await setup([{body:{type:"final_answer",output:"never"}}]);await new RunRepository(pool).requestCancellation(principal,setupResult.run.id);expect(await setupResult.worker.tick()).toBe(false);expect(setupResult.provider.calls).toBe(0);expect((await new RunRepository(pool).get(principal.tenantId,setupResult.run.id)).status).toBe("cancelled");});
  it("honors cancellation after invocation before completion",async()=>{let runId="";const replies:DeterministicReply[]=[{body:{type:"final_answer",output:"discard"},beforeReturn:async()=>{await new RunRepository(pool).requestCancellation(principal,runId);}}];const setupResult=await setup(replies);runId=setupResult.run.id;await expect(setupResult.worker.tick()).rejects.toThrow(/Cancellation/);expect((await new RunRepository(pool).get(principal.tenantId,runId)).status).toBe("cancelled");expect((await pool.query("SELECT status FROM model_attempts WHERE run_id=$1",[runId])).rows[0].status).toBe("cancelled");});
  it("enforces maximum steps before executing a proposed tool",async()=>{const {run,worker}=await setup([{body:{type:"call_tool",toolName:"calculator",arguments:{expression:"1+1"}}}],{tools:["calculator"],maxSteps:1});await expect(worker.tick()).rejects.toThrow(/Maximum step/);expect((await new RunRepository(pool).get(principal.tenantId,run.id)).status).toBe("failed");expect(Number((await pool.query("SELECT count(*) AS count FROM tool_executions WHERE run_id=$1",[run.id])).rows[0].count)).toBe(0);});
  it("enforces token and cost budgets",async()=>{const token=await setup([{body:{type:"final_answer",output:"too many"},usage:{inputTokens:20,outputTokens:20}}],{tokenBudget:10});await expect(token.worker.tick()).rejects.toThrow(/budget exceeded/);expect((await new RunRepository(pool).get(principal.tenantId,token.run.id)).status).toBe("failed");await pool.query("TRUNCATE audit_events,usage_records,model_attempts,tool_executions,worker_leases,checkpoints,steps,runs,agents CASCADE");const cost=await setup([{body:{type:"final_answer",output:"costly"},usage:{inputTokens:2,outputTokens:2}}],{costBudget:1,inputRate:1_000_000,outputRate:1_000_000});await expect(cost.worker.tick()).rejects.toThrow(/budget exceeded/);expect((await new RunRepository(pool).get(principal.tenantId,cost.run.id)).status).toBe("failed");});
});
