export const PRODUCT_HTML = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Durable Agent Platform</title><link rel="stylesheet" href="/app.css"></head><body><header><h1>Durable Agent Platform</h1><p>Canonical runtime control surface</p></header><section id="login" class="card"><h2>Workspace access</h2><p>Paste a JWT issued by your configured identity system. The platform validates tenant membership and roles.</p><input id="token" type="password" autocomplete="off" placeholder="Bearer token"><button id="connect">Connect</button><output id="login-status"></output></section><main id="app" hidden><nav><button data-view="dashboard">Dashboard</button><button data-view="agents">Agents</button><button data-view="runs">Runs</button><button data-view="approvals">Approvals</button><button data-view="memory">Memory</button><button data-view="knowledge">Knowledge</button><button data-view="connectors">Connectors</button><button data-view="members">Roles</button><button data-view="audit">Audit</button></nav><div id="identity" class="banner"></div>
<section id="dashboard" class="view"><h2>Dashboard</h2><button data-refresh>Refresh</button><div class="grid"><article><h3>Usage</h3><pre id="usage"></pre></article><article><h3>Providers</h3><pre id="providers"></pre></article><article><h3>Tools</h3><pre id="tools"></pre></article></div></section>
<section id="agents" class="view" hidden><h2>Agents</h2><form id="agent-form"><input name="name" placeholder="Agent name" required><textarea name="systemInstructions" placeholder="System instructions" required></textarea><select name="provider" id="agent-provider" aria-label="Configured provider" required></select><input name="model" placeholder="Model ID" required><input name="allowedTools" placeholder="Allowed tools, comma separated"><input name="maximumSteps" type="number" value="10" min="1"><input name="tokenBudget" type="number" value="10000" min="0"><input name="costBudgetMicrousd" type="number" value="0" min="0"><button>Create agent</button></form><form id="agent-patch-form"><input name="id" placeholder="Agent ID" required><input name="expectedVersion" type="number" placeholder="Expected version" required><textarea name="patch" placeholder='JSON patch, e.g. {"name":"Updated"}' required></textarea><button>Update agent</button></form><div id="agent-list"></div></section>
<section id="runs" class="view" hidden><h2>Runs and traces</h2><form id="run-form"><select name="agentId" id="run-agent" required></select><textarea name="goal" placeholder="Run goal" required></textarea><button>Start run</button></form><div id="run-list"></div><h3>Selected trace</h3><pre id="trace"></pre></section>
<section id="approvals" class="view" hidden><h2>Approval inbox</h2><div id="approval-list"></div></section>
<section id="memory" class="view" hidden><h2>Memory</h2><form id="memory-form"><select name="scope"><option>user</option><option>tenant</option></select><select name="memoryType"><option>note</option><option>fact</option><option>procedure</option><option>outcome</option></select><textarea name="text" placeholder="Memory content" required></textarea><input name="reason" placeholder="Creation reason" required><button>Store memory</button></form><div id="memory-list"></div></section>
<section id="knowledge" class="view" hidden><h2>Knowledge and retrieval</h2><form id="document-form"><input name="title" placeholder="Document title" required><select name="mediaType"><option>text/plain</option><option>text/markdown</option><option>application/json</option></select><select name="visibility"><option>private</option><option>tenant</option></select><textarea name="content" placeholder="Document content" required></textarea><button>Ingest document</button></form><form id="search-form"><input name="query" placeholder="Retrieval query" required><button>Search</button></form><pre id="search-results"></pre><div id="document-list"></div></section>
<section id="connectors" class="view" hidden><h2>Connectors</h2><form id="connector-form"><input name="name" placeholder="Connector name" required><input name="endpointUrl" type="url" placeholder="Allowlisted endpoint URL" required><input name="allowedTools" placeholder="Allowed remote tools, comma separated" required><input name="requiredRoles" placeholder="Execution roles, comma separated"><input name="credentialRef" placeholder="CONNECTOR_SECRET_* reference"><button>Register connector</button></form><div id="connector-list"></div></section>
<section id="members" class="view" hidden><h2>Workspace roles</h2><form id="member-form"><input name="identityId" placeholder="Identity UUID" required><select name="identityType"><option>user</option><option>service</option></select><input name="roles" placeholder="Roles, comma separated" required><button>Add membership</button></form><div id="member-list"></div></section>
<section id="audit" class="view" hidden><h2>Audit evidence</h2><div id="audit-list"></div></section><output id="notice"></output></main><script src="/app.js" defer></script></body></html>`;

export const PRODUCT_CSS = `:root{font-family:Inter,system-ui,sans-serif;color:#16202a;background:#f3f6f8}body{margin:0}header{background:#102b3f;color:white;padding:1.2rem 2rem}header h1,header p{margin:.2rem 0}.card,main{max-width:1200px;margin:1rem auto;padding:1rem}.card,.view,article{background:white;border:1px solid #d8e0e6;border-radius:8px}.view{padding:1rem;margin-top:1rem}nav{display:flex;gap:.4rem;flex-wrap:wrap}.banner{padding:.6rem;background:#dff4ea;margin-top:1rem;border-radius:6px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem}form{display:grid;gap:.6rem;padding:1rem 0;max-width:760px}input,textarea,select,button{font:inherit;padding:.55rem;border:1px solid #aab8c2;border-radius:5px}textarea{min-height:80px}button{cursor:pointer;background:#155e75;color:white;border:0}button.danger{background:#a52828}button.secondary{background:#526572}.item{border-top:1px solid #d8e0e6;padding:.8rem 0}.actions{display:flex;gap:.4rem;flex-wrap:wrap}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#eef3f6;padding:.7rem;border-radius:5px;max-height:430px;overflow:auto}output{display:block;padding:.5rem;color:#8b1d1d}@media(max-width:600px){header,.card,main{padding:.8rem;margin:.5rem}nav button{flex:1 1 40%}}`;

export const PRODUCT_JS = `"use strict";
const byId=(id)=>document.getElementById(id);let token=sessionStorage.getItem("dap_token")||"";let state={agents:[],runs:[]};
async function api(path,options={}){const headers={...(options.body?{"content-type":"application/json"}:{}),...(token?{authorization:"Bearer "+token}:{})};const response=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});let body=null;try{body=await response.json()}catch{}if(!response.ok)throw new Error((body&&body.message)||((body&&body.error)||("HTTP "+response.status)));return body}
function notice(message,error=false){byId("notice").textContent=message||"";byId("notice").style.color=error?"#8b1d1d":"#12613f"}
function values(form){return Object.fromEntries(new FormData(form).entries())}function csv(value){return String(value||"").split(",").map(v=>v.trim()).filter(Boolean)}
function list(id,items,actions=[]){const root=byId(id);root.replaceChildren();for(const item of items||[]){const row=document.createElement("div");row.className="item";const pre=document.createElement("pre");pre.textContent=JSON.stringify(item,null,2);row.append(pre);if(actions.length){const box=document.createElement("div");box.className="actions";for(const action of actions){const button=document.createElement("button");button.textContent=action.label;button.className=action.className||"secondary";button.onclick=()=>action.run(item);box.append(button)}row.append(box)}root.append(row)}}
async function optional(path){try{return await api(path)}catch(error){return {unavailable:error.message}}}
async function refresh(){const [me,agents,runs,approvals,usage,memories,documents,connectors,members,audit,providers,tools]=await Promise.all([api("/me"),api("/agents"),api("/runs"),api("/approvals"),optional("/usage"),optional("/memories"),optional("/documents"),optional("/connectors"),optional("/memberships"),optional("/audit?limit=30"),api("/providers"),api("/tools")]);state={agents,runs};byId("identity").textContent="Tenant "+me.tenantId+" · Identity "+me.userId+" · Roles "+me.roles.join(", ");byId("usage").textContent=JSON.stringify(usage,null,2);byId("providers").textContent=JSON.stringify(providers,null,2);byId("tools").textContent=JSON.stringify(tools,null,2);const providerSelect=byId("agent-provider");providerSelect.replaceChildren(...providers.map(p=>{const o=document.createElement("option");o.value=p.id;o.textContent=p.id;return o}));const select=byId("run-agent");select.replaceChildren(...agents.map(a=>{const o=document.createElement("option");o.value=a.id;o.textContent=a.name+" · "+a.model_config.provider+"/"+a.model_config.model;return o}));list("agent-list",agents);list("run-list",runs,[{label:"Trace",run:showTrace},{label:"Cancel",className:"danger",run:cancelRun}]);list("approval-list",approvals,[{label:"Approve",run:a=>decision(a,"approve")},{label:"Reject",className:"danger",run:a=>decision(a,"reject")}]);list("memory-list",Array.isArray(memories)?memories:[memories],[{label:"Delete",className:"danger",run:deleteMemory}]);list("document-list",Array.isArray(documents)?documents:[documents],[{label:"Delete",className:"danger",run:deleteDocument}]);list("connector-list",Array.isArray(connectors)?connectors:[connectors],[{label:"Discover",run:discoverConnector},{label:"Revoke",className:"danger",run:revokeConnector}]);list("member-list",Array.isArray(members)?members:[members],[{label:"Revoke",className:"danger",run:revokeMember}]);list("audit-list",Array.isArray(audit)?audit:[audit]);notice("Refreshed")}
async function showTrace(run){byId("trace").textContent=JSON.stringify(await api("/runs/"+run.id+"/trace"),null,2)}async function cancelRun(run){await api("/runs/"+run.id+"/cancel",{method:"POST"});await refresh()}async function decision(a,d){await api("/approvals/"+a.id+"/"+d,{method:"POST",body:JSON.stringify({comment:"Decision from product UI"})});await refresh()}
async function deleteMemory(m){await api("/memories/"+m.id,{method:"DELETE",body:JSON.stringify({reason:"Deleted from product UI"})});await refresh()}async function deleteDocument(d){await api("/documents/"+d.id,{method:"DELETE",body:JSON.stringify({reason:"Deleted from product UI"})});await refresh()}async function discoverConnector(c){await api("/connectors/"+c.id+"/discover",{method:"POST"});await refresh()}async function revokeConnector(c){await api("/connectors/"+c.id+"/revoke",{method:"POST",body:JSON.stringify({reason:"Revoked from product UI"})});await refresh()}async function revokeMember(m){await api("/memberships/"+m.identity_id+"/revoke",{method:"POST"});await refresh()}
byId("connect").onclick=async()=>{token=byId("token").value.trim();sessionStorage.setItem("dap_token",token);try{await refresh();byId("login").hidden=true;byId("app").hidden=false}catch(error){byId("login-status").textContent=error.message}};byId("token").value=token;
document.querySelectorAll("nav button").forEach(button=>button.onclick=()=>document.querySelectorAll(".view").forEach(view=>view.hidden=view.id!==button.dataset.view));document.querySelectorAll("[data-refresh]").forEach(button=>button.onclick=()=>refresh().catch(e=>notice(e.message,true)));
byId("agent-form").onsubmit=async event=>{event.preventDefault();const v=values(event.target);await api("/agents",{method:"POST",body:JSON.stringify({name:v.name,systemInstructions:v.systemInstructions,model:{provider:v.provider,model:v.model},allowedTools:csv(v.allowedTools),maximumSteps:Number(v.maximumSteps),tokenBudget:Number(v.tokenBudget),costBudgetMicrousd:Number(v.costBudgetMicrousd),approvalPolicy:{},outputSchema:null})});event.target.reset();await refresh()};
byId("agent-patch-form").onsubmit=async event=>{event.preventDefault();const v=values(event.target);await api("/agents/"+v.id,{method:"PATCH",body:JSON.stringify({expectedVersion:Number(v.expectedVersion),...JSON.parse(v.patch)})});await refresh()};
byId("run-form").onsubmit=async event=>{event.preventDefault();const v=values(event.target);await api("/agents/"+v.agentId+"/runs",{method:"POST",body:JSON.stringify({goal:v.goal})});event.target.reset();await refresh()};
byId("memory-form").onsubmit=async event=>{event.preventDefault();const v=values(event.target);await api("/memories",{method:"POST",body:JSON.stringify({scope:v.scope,agentId:null,memoryType:v.memoryType,content:{text:v.text,attributes:{}},provenance:{source:"product_ui"},creationReason:v.reason,sourceRunId:null,relevance:{tags:[],importance:.5},retentionUntil:null})});event.target.reset();await refresh()};
byId("document-form").onsubmit=async event=>{event.preventDefault();const v=values(event.target);await api("/documents",{method:"POST",body:JSON.stringify({title:v.title,mediaType:v.mediaType,content:v.content,visibility:v.visibility,sourceUri:null,metadata:{}})});event.target.reset();await refresh()};
byId("search-form").onsubmit=async event=>{event.preventDefault();const v=values(event.target);byId("search-results").textContent=JSON.stringify(await api("/retrieval/search",{method:"POST",body:JSON.stringify({query:v.query,metadata:{},maxChunks:5,maxTokens:2000,minimumScore:.2})}),null,2)};
byId("connector-form").onsubmit=async event=>{event.preventDefault();const v=values(event.target);await api("/connectors",{method:"POST",body:JSON.stringify({name:v.name,transport:"mcp_streamable_http",endpointUrl:v.endpointUrl,credentialRef:v.credentialRef||null,allowedTools:csv(v.allowedTools),requiredRoles:csv(v.requiredRoles),rateLimitPerMinute:60})});event.target.reset();await refresh()};
byId("member-form").onsubmit=async event=>{event.preventDefault();const v=values(event.target);await api("/memberships",{method:"POST",body:JSON.stringify({identityId:v.identityId,identityType:v.identityType,roles:csv(v.roles)})});event.target.reset();await refresh()};
window.addEventListener("unhandledrejection",event=>notice(event.reason&&event.reason.message||String(event.reason),true));if(token)byId("connect").click();`;
